entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

providers:
  docker:
    network: traefik
    exposedByDefault: false
  file:
    directory: ./external
    watch: true

api:
  insecure: false
  dashboard: true

log:
  level: DEBUG
